# Generated by Django 5.0 on 2023-12-29 14:48

import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expiresAt',
            field=models.DateTimeField(null=True, verbose_name=job.models.expireDate),
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('Training', 'Training'), ('Internship', 'Internship'), ('FullTime', 'Fulltime'), ('PartTime', 'Parttime')], default='Training', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('SSC or equivalent', 'Ssc'), ('HSC or equivalent', 'Hsc'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Any', 'Any')], default='Any', max_length=25),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
