# Generated by Django 5.0 on 2023-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_company_job_createdat_job_expiresat_job_jobtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('Any', 'Any'), ('SSC or equivalent', 'Ssc'), ('HSC or equivalent', 'Hsc'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default='Any', max_length=25),
        ),
    ]
